<a href="https://colab.research.google.com/github/radu93/graph_learning/blob/main/Node_Classification_with_GAT_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Node Classification



## Initial imports

In [ ]:
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

1.11.0+cu113


In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

## Implementing the forward method

### Linear Transformation

Consider the node $i$ with feature vector $\bar{h}_i\in\mathbb R^{F}$. We apply a linear transformation to get a new feature vector $\bar{h'}_i \in \mathbb{R}^{F'}$:
$$
\bar{h'}_i = \textbf{W}\cdot \bar{h}_i
$$
with $\textbf{W}\in\mathbb R^{F'\times F}$.

The following code is a sample linear transformation applied over *nb_nodes*.

In [ ]:
in_features = 5
out_features = 2
nb_nodes = 3

W = nn.Parameter(torch.zeros(size=(in_features, out_features))) # xavier paramiter inizializator
nn.init.xavier_uniform_(W.data, gain=1.414)

print(W)

input = torch.rand(nb_nodes, in_features) 

print(input)

# linear transformation
h = torch.mm(input, W)
N = h.size()[0]

print(h.shape)

Parameter containing:
tensor([[-0.7644,  0.8916],
        [-0.8917,  0.4089],
        [ 0.8180, -1.1785],
        [-1.0833,  1.1294],
        [ 1.0618,  0.1176]], requires_grad=True)
tensor([[6.9035e-01, 1.5097e-01, 3.3485e-01, 4.2646e-02, 2.0596e-01],
        [3.5916e-01, 8.5551e-01, 4.5568e-04, 6.8080e-02, 4.2548e-01],
        [4.1077e-01, 1.5948e-01, 2.6342e-01, 4.9429e-01, 1.1808e-01]])
torch.Size([3, 2])


### Attention Mechanism

This is an exemplification of the attention mechanism. Its purpose is to add learnable weights between neighboring nodes.

![title](https://github.com/AntonioLonga/PytorchGeometricTutorial/blob/main/Tutorial3/AttentionMechanism.png?raw=1)

Initialize the attention weights vector $a\in\mathbb{R}^{2F'}$. This vector acts like a global filter of learnable weights between neighboring nodes.

In [ ]:
a = nn.Parameter(torch.zeros(size=(2*out_features, 1))) # xavier paramiter inizializator
nn.init.xavier_uniform_(a.data, gain=1.414)
print(a.shape)
print(a)

leakyrelu = nn.LeakyReLU(0.2)  # LeakyReLU

torch.Size([4, 1])
Parameter containing:
tensor([[0.8732],
        [0.2180],
        [1.3072],
        [1.3225]], requires_grad=True)


Compute $a_{input}\in\mathbb R^{N \times N \times 2F'}$, where $N$ is the number of nodes in the graph. It encodes all possible pairs of nodes together with their concatenated feature vectors.

In [ ]:
a_input = torch.cat([h.repeat(1, N).view(N * N, -1), h.repeat(N, 1)], dim=1).view(N, -1, 2 * out_features)

print(a_input)

tensor([[[-0.2159,  0.3550, -0.2159,  0.3550],
         [-0.2159,  0.3550, -0.6590,  0.7964],
         [-0.2159,  0.3550, -0.6508,  0.6931]],

        [[-0.6590,  0.7964, -0.2159,  0.3550],
         [-0.6590,  0.7964, -0.6590,  0.7964],
         [-0.6590,  0.7964, -0.6508,  0.6931]],

        [[-0.6508,  0.6931, -0.2159,  0.3550],
         [-0.6508,  0.6931, -0.6590,  0.7964],
         [-0.6508,  0.6931, -0.6508,  0.6931]]], grad_fn=<ViewBackward0>)


![title](https://github.com/AntonioLonga/PytorchGeometricTutorial/blob/main/Tutorial3/a_input.png?raw=1)

The multiplication $a_{input} \times a$ encodes the application of the filter $a$ over all the nodes. Note that for this exemplification we did not consider any adjacency matrix, so each node is connected with every other node (similar to a complete graph).
The result is passed through a LeakyReLU and stored in $e\in\mathbb{R}^{N \times N}$.

In [ ]:
e = leakyrelu(torch.matmul(a_input, a).squeeze(2))

In [ ]:
print(a_input.shape, a.shape)
print("")
print(torch.matmul(a_input, a).shape)
print("")
print(torch.matmul(a_input, a).squeeze(2).shape)

torch.Size([3, 3, 4]) torch.Size([4, 1])

torch.Size([3, 3, 1])

torch.Size([3, 3])


In [ ]:
print(e)
print(e.shape)

tensor([[ 0.0760,  0.0805, -0.0090],
        [-0.0429, -0.0420, -0.0672],
        [-0.0460, -0.0451, -0.0702]], grad_fn=<LeakyReluBackward0>)
torch.Size([3, 3])


### Masked Attention

Let's now consider a random adjacency matrix, in order to get closer to a real graph.

In [ ]:
# Masked Attention
adj = torch.randint(2, (3, 3))

print('adj:')
print(adj)

zero_vec  = -9e15 * torch.ones_like(e)
print(zero_vec.shape)

adj:
tensor([[0, 0, 0],
        [0, 0, 1],
        [1, 0, 0]])
torch.Size([3, 3])


The previous result $e\in\mathbb{R}^{N \times N}$ includes every possible edge between $N$ graph nodes. We select from $e$ only the edges specified by the adjacency matrix.

In [ ]:
attention = torch.where(adj > 0, e, zero_vec)
print(adj,"\n",e,"\n",zero_vec)
print('attention:\n', attention)
print('attention shape:\n', attention.shape)


tensor([[0, 0, 0],
        [0, 0, 1],
        [1, 0, 0]]) 
 tensor([[ 0.0760,  0.0805, -0.0090],
        [-0.0429, -0.0420, -0.0672],
        [-0.0460, -0.0451, -0.0702]], grad_fn=<LeakyReluBackward0>) 
 tensor([[-9.0000e+15, -9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15, -9.0000e+15]])
attention:
 tensor([[-9.0000e+15, -9.0000e+15, -9.0000e+15],
        [-9.0000e+15, -9.0000e+15, -6.7187e-02],
        [-4.6002e-02, -9.0000e+15, -9.0000e+15]], grad_fn=<SWhereBackward0>)
attention shape:
 torch.Size([3, 3])


Now, pass the result through a softmax layer.

In [ ]:
attention = F.softmax(attention, dim=1)
h_prime   = torch.matmul(attention, h)

In [ ]:
attention

tensor([[0.3333, 0.3333, 0.3333],
        [0.0000, 0.0000, 1.0000],
        [1.0000, 0.0000, 0.0000]], grad_fn=<SoftmaxBackward0>)

In [ ]:
h_prime

tensor([[-0.5086,  0.6148],
        [-0.6508,  0.6931],
        [-0.2159,  0.3550]], grad_fn=<MmBackward0>)

This is the effect of applying an attention filter over node features:

In [ ]:
print(h_prime,"\n",h)

tensor([[-0.5086,  0.6148],
        [-0.6508,  0.6931],
        [-0.2159,  0.3550]], grad_fn=<MmBackward0>) 
 tensor([[-0.2159,  0.3550],
        [-0.6590,  0.7964],
        [-0.6508,  0.6931]], grad_fn=<MmBackward0>)


# Building a basic Attentional Layer

This part puts together all the building blocks and implements a Graph Attentional Layer as a PyTorch Module.

In [ ]:
class GATLayer(nn.Module):
    def __init__(self, in_features, out_features, dropout=0.6, alpha=0.2, concat=True):
        super(GATLayer, self).__init__()
        self.dropout       = dropout        # drop prob = 0.6
        self.in_features   = in_features    # 
        self.out_features  = out_features   # 
        self.alpha         = alpha          # LeakyReLU with negative input slope, alpha = 0.2
        self.concat        = concat         # conacat = True for all layers except the output layer.

        # Xavier Initialization of Weights
        self.W = nn.Parameter(torch.zeros(size=(in_features, out_features)))
        nn.init.xavier_uniform_(self.W.data, gain=1.414)
        
        self.a = nn.Parameter(torch.zeros(size=(2*out_features, 1)))
        nn.init.xavier_uniform_(self.a.data, gain=1.414)
        
        # LeakyReLU
        self.leakyrelu = nn.LeakyReLU(self.alpha)

    def forward(self, input, adj):
        # Linear Transformation
        h = torch.mm(input, self.W) # matrix multiplication
        N = h.size()[0]

        # Attention Mechanism
        a_input = torch.cat([h.repeat(1, N).view(N * N, -1), h.repeat(N, 1)], dim=1).view(N, -1, 2 * self.out_features)
        e       = self.leakyrelu(torch.matmul(a_input, self.a).squeeze(2))

        # Masked Attention
        zero_vec  = -9e15*torch.ones_like(e)
        attention = torch.where(adj > 0, e, zero_vec)
        
        attention = F.softmax(attention, dim=1)
        attention = F.dropout(attention, self.dropout, training=self.training)
        h_prime   = torch.matmul(attention, h)

        if self.concat:
            return F.elu(h_prime)
        else:
            return h_prime

# Testing

## Cora Dataset

We will use **Cora**, a citation graph containing 2708 scientific publications. For each publication there is a 1433-dimensional feature vector, which is a bag-of-words representation (with a small, fixed dictionary) of the paper text. The edges in this graph represent citations, and are commonly treated as undirected. The goal is to classify each paper into one of seven classes (topics).

Load and inspect the Cora dataset using the PyTorch Geometric library:

In [ ]:
from torch_geometric.data import Data
from torch_geometric.nn import GATConv
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T

import matplotlib.pyplot as plt

name_data = 'Cora'
dataset = Planetoid(root= '/tmp/' + name_data, name = name_data)
dataset.transform = T.NormalizeFeatures()

print(f'Number of graphs: {len(dataset)}')
print(f'Number of features: {dataset.num_features}')
print(f'Number of classes: {dataset.num_classes}')
print()

g0_data = dataset[0]
print(g0_data)
print(f'Number of nodes: {g0_data.num_nodes}')
print(f'Number of edges: {g0_data.num_edges}')
print(f'Average node degree: {g0_data.num_edges / g0_data.num_nodes:.2f}')
print(f'Number of training nodes: {g0_data.train_mask.sum()}')
print(f'Number of validation nodes: {g0_data.val_mask.sum()}')
print(f'Number of test nodes: {g0_data.test_mask.sum()}')
print()

print('Train mask:')
print(g0_data.train_mask)
print('Edge index:')
print(g0_data.edge_index)
print()

# Some more utility functions on a Data object 
print(f'Contains isolated nodes: {g0_data.has_isolated_nodes()}')
print(f'Contains self-loops: {g0_data.has_self_loops()}')
print(f'Is undirected: {g0_data.is_undirected()}')

Number of graphs: 1
Number of features: 1433
Number of classes: 7

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])
Number of nodes: 2708
Number of edges: 10556
Average node degree: 3.90
Number of training nodes: 140
Number of validation nodes: 500
Number of test nodes: 1000

Train mask:
tensor([ True,  True,  True,  ..., False, False, False])
Edge index:
tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])

Contains isolated nodes: False
Contains self-loops: False
Is undirected: True


## GAT Network

We use a GAT Network with 2 Attentional Layers.

The first layer uses a multi-head attention. This means it applies the attentional convolution multiple times and stacks the results. The dimension of its output features is $8 \times 8$ for each node (8 heads with 8 output features each).

The second layer gets the linearized 64 features and outputs 7 features.

One of the main advantages of attentional convolution is that the entire graph must not need to be known in advance. However, in this experiment we introduce the entire Cora graph into the model at each training epoch. A possible approach that would leverage the aforementioned property might be to feed the Cora graph into the model node by node during the training phase.

### Using GATConv Layers

For the first test, we use the [`GATConv`](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GATConv) layer offered by PyTorch.

In [ ]:
class GAT(torch.nn.Module):
    def __init__(self):
        super(GAT, self).__init__()
        self.hid = 8
        self.in_head = 8
        self.out_head = 1
        
        self.conv1 = GATConv(dataset.num_features, self.hid, heads=self.in_head, dropout=0.6)
        self.conv2 = GATConv(self.hid*self.in_head, dataset.num_classes, concat=False,
                             heads=self.out_head, dropout=0.6)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
                
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv1(x, edge_index)
        x = F.elu(x)
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv2(x, edge_index)
        
        return F.log_softmax(x, dim=1)

We train the model using and Adam optimizer for 1000 epochs. Each epoch feeds the entire Cora graph into the network. The computed loss takes into consideration only the nodes from the training set.

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = "cpu"

model = GAT().to(device)
print(model)

data = dataset[0].to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)

model.train()
for epoch in range(1000):
    model.train()
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    
    if epoch%200 == 0:
        print(loss)
    
    loss.backward()
    optimizer.step()
    
    

GAT(
  (conv1): GATConv(1433, 8, heads=8)
  (conv2): GATConv(64, 7, heads=1)
)
tensor(1.9487, grad_fn=<NllLossBackward0>)
tensor(0.6854, grad_fn=<NllLossBackward0>)
tensor(0.5262, grad_fn=<NllLossBackward0>)
tensor(0.5165, grad_fn=<NllLossBackward0>)
tensor(0.5837, grad_fn=<NllLossBackward0>)


Evaluate the model prediction for the nodes in the testing set. It should get at least 82% accuracy.

In [ ]:
model.eval()
_, pred = model(data).max(dim=1)
correct = float(pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
acc = correct / data.test_mask.sum().item()
print('Accuracy: {:.4f}'.format(acc))

print(pred[data.test_mask])

Accuracy: 0.8190
tensor([2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2,
        2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 6, 5, 4, 4, 4, 1, 1, 1, 1, 1, 1, 6,
        2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5,
        5, 5, 2, 2, 2, 2, 2, 6, 6, 1, 0, 0, 0, 0, 5, 0, 0, 0, 3, 0, 0, 6, 0, 6,
        3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3,
        3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 4, 4, 4, 4, 4, 3, 2, 5, 5, 5, 5,
        6, 5, 5, 5, 5, 6, 4, 3, 0, 0, 1, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0,
        0, 0, 0, 0, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4,
        6, 6, 5, 6, 6, 0, 5, 5, 5, 0, 5, 4, 4, 0, 3, 3, 3, 2, 3, 1, 3, 3, 3, 6,
        3, 3, 1, 3, 3, 

### Using our basic Layer

For this test, we use the GATLayer that we manually implemented above. We use the same architecture for the network.

In [ ]:
class GATBasic(torch.nn.Module):
    def __init__(self):
        super(GATBasic, self).__init__()
        self.hid = 8
        self.in_head = 8

        # multi head attention
        self.attentions = [ GATLayer(dataset.num_features, self.hid, concat=True) for _ in range(self.in_head) ]
        for i, attention in enumerate(self.attentions):
            self.add_module('attention_{}'.format(i), attention)

        # single head attention output layer
        self.conv2 = GATLayer(self.hid * self.in_head, dataset.num_classes, concat=False)

    def forward(self, x, adj):
      x = F.dropout(x, p=0.6, training=self.training)
      x = torch.cat([ att(x, adj) for att in self.attentions ], dim=1)
      x = F.dropout(x, p=0.6, training=self.training)
      x = self.conv2(x, adj)
      x = F.log_softmax(x, dim=1)

      return x

Unfortunately, our implementation uses extremely large matrix multiplications which are not optimized. Recall that $a_{input}\in\mathbb R^{N \times N \times 2F'}$ and it includes every pair of nodes, most of which are not linked in the  Cora graph. For this reason, the training is slow compared to the PyTorch GATConv Layers.

However, training the model for 500 epochs gets an accuracy of about 80%.



In [ ]:
from torch_geometric.utils import to_dense_adj

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = "cpu"

model = GATBasic().to(device)
print(model)

data = dataset[0].to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)

features = data.x
adj = to_dense_adj(data.edge_index)[0]

model.train()
for epoch in range(500):
    model.train()
    optimizer.zero_grad()
    out = model(features, adj)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    
    if epoch%10 == 0:
        print(loss)
    
    loss.backward()
    optimizer.step()

GATBasic(
  (attention_0): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (attention_1): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (attention_2): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (attention_3): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (attention_4): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (attention_5): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (attention_6): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (attention_7): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
  (conv2): GATLayer(
    (leakyrelu): LeakyReLU(negative_slope=0.2)
  )
)
tensor(1.9518, grad_fn=<NllLossBackward0>)
tensor(1.8696, grad_fn=<NllLossBackward0>)
tensor(1.7932, grad_fn=<NllLossBackward0>)
tensor(1.6408, grad_fn=<NllLossBackward0>)
tensor(1.5401, grad_fn=<NllLossBackward0>)
tensor(1.4727, grad_fn=<NllLossBackward0>)
tensor(1.3327, grad_fn=<NllLossBac

Evaluate the model prediction for the nodes in the testing set. It should get at least 80% accuracy.

In [ ]:
model.eval()
_, pred = model(features, adj).max(dim=1)
correct = float(pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
acc = correct / data.test_mask.sum().item()
print('Accuracy: {:.4f}'.format(acc))

print(pred[data.test_mask])

Accuracy: 0.8090
tensor([3, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 6, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 6,
        2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5,
        5, 5, 2, 2, 2, 2, 2, 6, 6, 1, 0, 0, 0, 0, 5, 0, 0, 0, 3, 0, 0, 6, 0, 0,
        1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 4, 4, 4, 4, 4, 3, 2, 5, 5, 5, 5,
        6, 5, 5, 5, 5, 6, 4, 4, 0, 0, 1, 0, 3, 0, 6, 6, 6, 6, 6, 6, 3, 0, 0, 0,
        0, 0, 0, 0, 3, 4, 0, 3, 3, 3, 3, 3, 3, 4, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4,
        6, 6, 5, 6, 0, 0, 5, 5, 5, 0, 5, 0, 4, 0, 3, 3, 3, 2, 3, 1, 3, 3, 3, 3,
        3, 3, 1, 0, 1, 

# References

This demo is based on the skeleton code from the following tutorials:
https://colab.research.google.com/github/AntonioLonga/PytorchGeometricTutorial/blob/main/Tutorial3/Tutorial3.ipynb
https://colab.research.google.com/drive/1aA--IgJSdPh7J_MIJgs2r0D0VCbGpNTp#scrollTo=Cs42Utl2Hj8O

It adds the implementation and testing of the basic GAT network, as long as extra explanations.